apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-pagamentos
  namespace: lanchonete
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-pagamentos
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50