apiVersion: v1
kind: Service
metadata:
  name: app-pagamentos
  namespace: lanchonete
spec:
  selector:
    app: app-pagamentos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: LoadBalancer/home/leonardoreis/code/fiap/github.com/lanchonete/deployments