version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 7000
      NODE_ENV: dev
      DATABASE_URL: postgresql://postgres:postgres@db:5432/lanchonete?schema=public
    ports:
      - 7000:7000
    command: sh -c "npx prisma migrate deploy && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonete
    ports:
      - 5432:5432

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./tooling/swagger/swagger.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

networks:
    default:
        name: lanchonete-network
