services:
  app:
    container_name: lanchonete-pagamentos
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 7000
      NODE_ENV: dev
      DATABASE_URL: mongodb+srv://pagamento:<lanchonete>@pagamentos.djvoood.mongodb.net/?retryWrites=true&w=majority&appName=pagamentos
    ports:
      - 7000:7000
    # command: sh -c "npx prisma migrate deploy && npm run dev"
    command: sh -c "npm run dev"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-pagamentos"
    ports:
      - "8082:8080"
    volumes:
      - ./tooling/swagger/swagger.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

networks:
    default:
        name: lanchonete-pagamentos-network
