version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-pagamentos
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 7003
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/lanchonete?schema=public
      TOKEN_MERCADO_PAGO_DEV: TEST-3012597545599426-051414-ffccb6c232ef1ade75243761b1e67a39-73897475
      MICROSERVICO_OPERACAO_URL: http://localhost:7000
    ports:
      - 7003:7003

networks:
    default:
        name: lanchonete-network
